# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170405_0139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tags',
            new_name='categories',
        ),
    ]
